export const WINSTON_LOGGER_TOKEN = Symbol('WINSTON_LOGGER_TOKEN');
export const LOGGING_PROVIDER_OPTIONS_TOKEN = Symbol('LOGGING_PROVIDER_OPTIONS_TOKEN');
export const LOGGING_PROVIDER_PORT = Symbol('LOGGING_PROVIDER_PORT');