export const CACHE_PROVIDER_MODULE_TOKEN = Symbol('CACHE_PROVIDER_MODULE_TOKEN');
export const MEMCACHED_CLIENT_TOKEN = Symbol('MEMCACHED_CLIENT_TOKEN');
export const CACHE_PROVIDER_SERVICE_TOKEN = Symbol('CACHE_PROVIDER_SERVICE_TOKEN');
