export enum BookGenreEnum {
    FICTION = 'FICTION',
    NON_FICTION = 'NON_FICTION',
    MYSTERY = 'MYSTERY',
    FANTASY = 'FANTASY',
    SCIENCE_FICTION = 'SCIENCE_FICTION',
    BIOGRAPHY = 'BIOGRAPHY',
    HISTORY = 'HISTORY',
    ROMANCE = 'ROMANCE',
    HORROR = 'HORROR',
    THRILLER = 'THRILLER',
    SELF_HELP = 'SELF_HELP',
    CHILDREN = 'CHILDREN',
    YOUNG_ADULT = 'YOUNG_ADULT',
    POETRY = 'POETRY',
    GRAPHIC_NOVEL = 'GRAPHIC_NOVEL',
    CLASSIC = 'CLASSIC',
    OTHER = 'OTHER'
}